package com.example.entity.jpa1;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity.jpa1.DateTimeTest")
@Table(name = "date_time_test")
public class DateTimeTest implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "`id`", nullable = false)
  private Integer id;
  @Column(name = "`test_date`", nullable = false)
  private Date testDate;
  @Column(name = "`test_time_tz`", nullable = false)
  private Time testTimeTz;
  @Column(name = "`test_time`", nullable = false)
  private Time testTime;
  @Column(name = "`test_datetime_tz`", nullable = false)
  private Timestamp testDatetimeTz;
  @Column(name = "`test_datetime`", nullable = false)
  private Timestamp testDatetime;
}